name: 'smap_analytics'
version: '1.0.0'
config-version: 2

profile: 'smap_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  smap_analytics:
    # Staging models are materialized as views
    staging:
      +materialized: view
      +schema: staging
    
    # Marts (dimensions/facts) are materialized as tables
    marts:
      +materialized: table
      +schema: analytics

snapshots:
  smap_analytics:
    +schema: snapshots
